src/Entity/Loan.php
<?php

namespace App\Entity;

use App\Repository\LoanRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

enum LoanStatus: int {
    case PENDING = 0;
    case ACCEPTED = 1;
    case REFUSED = 2;
    case RETURNED = 3;
    case CANCELLED_BY_LOANER = 4;
}

#[ORM\Entity(repositoryClass: LoanRepository::class)]
class Loan
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $departure_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $return_date = null;

    #[ORM\ManyToMany(targetEntity: Equipment::class, inversedBy: 'loans', fetch:'EAGER')]
    private Collection $equipmentLoaned;

    #[ORM\Column]
    private ?int $status = 0;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $comment = null;

    #[ORM\ManyToOne(inversedBy: 'loans')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $loaner = null;

    #[ORM\Column(type: Types::ARRAY, nullable: true)]
    private ?array $discriminators = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $adminComment = null;

    #[ORM\ManyToOne]
    private ?User $assignee = null;

    public function __construct()
    {
        $this->equipmentLoaned = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->id;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDepartureDate(): ?\DateTimeInterface
    {
        return $this->departure_date;
    }

    public function setDepartureDate(\DateTimeInterface $departure_date): static
    {
        $this->departure_date = $departure_date;

        return $this;
    }

    public function getReturnDate(): ?\DateTimeInterface
    {
        return $this->return_date;
    }

    public function setReturnDate(\DateTimeInterface $return_date): static
    {
        $this->return_date = $return_date;

        return $this;
    }

    /**
     * @return Collection<int, Equipment>
     */
    public function getEquipmentLoaned(): Collection
    {
        return $this->equipmentLoaned;
    }

    public function addEquipmentLoaned(Equipment $equipmentLoaned): static
    {
        if (!$this->equipmentLoaned->contains($equipmentLoaned)) {
            $this->equipmentLoaned->add($equipmentLoaned);
        }

        return $this;
    }

    public function removeEquipmentLoaned(Equipment $equipmentLoaned): static
    {
        $this->equipmentLoaned->removeElement($equipmentLoaned);

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): static
    {
        $this->comment = $comment;

        return $this;
    }

    public function getLoaner(): ?User
    {
        return $this->loaner;
    }

    public function setLoaner(?User $loaner): static
    {
        $this->loaner = $loaner;

        return $this;
    }

    public function getDiscriminators(): ?array
    {
        return $this->discriminators;
    }

    public function setDiscriminators(?array $discriminators): static
    {
        $this->discriminators = $discriminators;

        return $this;
    }

    public function getAdminComment(): ?string
    {
        return $this->adminComment;
    }

    public function setAdminComment(?string $adminComment): static
    {
        $this->adminComment = $adminComment;

        return $this;
    }

    public function getAssignee(): ?User
    {
        return $this->assignee;
    }

    public function setAssignee(?User $assignee): static
    {
        $this->assignee = $assignee;

        return $this;
    }
}

src/Controller/PdfController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Attribute\Route;
use App\Entity\Loan;
/*
use Symfony\Component\Routing\Generator\UrlGenerator;
use Knp\Bundle\SnappyBundle\Snappy\Response\PdfResponse;
use Knp\Snappy\Pdf;
*/


class PdfController extends AbstractController
{
    /*
    #[Route('/pdf/loan/{id}', name: 'pdf_loan')]
    public function pdfLoan(string $id, Pdf $knpSnappyPdf)
    {
        $pageUrl = $this->generateUrl('pdf_loan_html', ['id' => $id], UrlGenerator::ABSOLUTE_URL);

        $knpSnappyPdf->setOption('no-outline', true);
        $knpSnappyPdf->setOption('page-size','LETTER');
        $knpSnappyPdf->setOption('encoding', 'UTF-8');

        return new PdfResponse(
            $knpSnappyPdf->getOutput($pageUrl)
        );
    }
    */

    #[Route('/pdf/loan_html/{id}', name: 'pdf_loan_html')]
    public function loanAction(Loan $loan)
    {
        if ($loan->getLoaner() !== $this->getUser()) {
            $this->addFlash('error', 'Vous ne pouvez pas accéder à ce document.');
            return $this->redirectToRoute('app_main');
        }

        return $this->render('pdf/loan.html.twig', [
            'loan' => $loan
        ]);
    }
}

templates/pdf/loan.html.twig
{% extends "base.html.twig" %}
{% block title %} MATOS Emprunt #{{ loan.id }}{% endblock %}
{% block body %}
<style>
    html {
        background-color: white !important;
    }
    @media print
    {    
        .no-print, .no-print *
        {
            display: none !important;
        }
    }
</style>
{% if loan.status != 1 %}
    <p>Erreur, cet emprunt n'est pas/plus valide !</p>

    <small>MATOS - IUT de Troyes - 2024</small>
{% else %}
    <p class="no-print text-center my-5 text-lg italic text-slate-500">
        Pour imprimer cette page, cliquez sur le bouton d'impression de votre navigateur ou appuyez sur <kbd>Ctrl</kbd> + <kbd>P</kbd>.
    </p>
    <div class="flex">
        <img src="{{ asset('logo_bw_lowink.png') }}" alt="Logo" class="w-32 h-32">
        <div class="ml-4">
            <p class="text-4xl">MATOS</p>
            <p class="text-xl">IUT de Troyes</p>
            <p class="text-3xl">{{ loan.loaner.name }}</p>
            <p class="text-sm">{{ loan.loaner.email }}</p>
        </div>
    </div>
    <p class="text-md text-gray-500 mt-5 mb-3">
        <b>HORAIRES :</b>
    </p>
    <p class="text-xl pl-5 ">
        Date de départ : <b class="text-gray-500">{{ loan.departureDate|date('d/m/Y H:i') }}</b>
    </p>
    <p class="text-xl pl-5">
        Date de retour : <b class="text-gray-500">{{ loan.returnDate|date('d/m/Y H:i') }}</b>
    </p>
    <p class="text-md text-gray-500 mt-5 mb-3">
        <b>MATÉRIEL EMPRUNTÉ :</b>
    </p>
    <div>
        {% for equipment in loan.equipmentLoaned %}
            <div class="mt-2 ml-5 text-md flex">
                <div class="w-6 h-6 mr-1 border-2 rounded-md" style="border-color:slategray"></div>
                {{ equipment.name }} {% if loan.discriminators[equipment.id] is defined %} (N°{{ loan.discriminators[equipment.id] }}) {% endif %} 
            </div>
        {% endfor %}
    </div>
    <p class="text-md text-gray-500 mt-5 mb-3">
        <b>COMMENTAIRE :</b>
    </p>
    <p class="ml-5">{{ loan.comment ?? "<i>Aucun</i>" }}</p>

    <div class="absolute bottom-3 w-screen">
        <div class="text-xs text-center">Imprimez ce document en noir et blanc, en pleine page au format A4 ou A5 (demi A4). Document conçu avec conscience écologique sur le site {{ url('app_main') }}.</div>
        <div class="text-xs text-center">MATOS - #{{ loan.id }} - IUT de Troyes - {{ loan.departureDate|date('Y') }}</div>
    </div>
{% endif %}
{% endblock %}